name: MLflow CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MLflow + deps
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn joblib

      - name: Run MLflow Project (Training)
        env:
          MLFLOW_EXPERIMENT_NAME: credit_scoring_ci
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/MLProject/mlruns
          DO_TUNING: "1"
          TARGET_COL: "Y"
        run: |
          cd MLProject
          mlflow run . --env-manager=local | tee run.log

          # Ambil RUN_ID dari log mlflow run
          RUN_ID=$(grep -oP "run with ID '\K[0-9a-f]{32}(?='" run.log | tail -n 1)

          if [ -z "$RUN_ID" ]; then
            echo "ERROR: RUN_ID tidak ketemu dari output mlflow run"
            echo "=== run.log ==="
            cat run.log
            exit 1
          fi

          echo "Using RUN_ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build Docker Image with MLflow
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/MLProject/mlruns
        run: |
          cd MLProject
          echo "Using RUN_ID: $RUN_ID"
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n credit-scoring-mlflow

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag & Push Docker Image
        run: |
          docker tag credit-scoring-mlflow "${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-mlflow:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-mlflow:latest"