name: MLflow CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MLflow + deps
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn joblib

      - name: Run MLflow Project (Training)
        env:
          MLFLOW_EXPERIMENT_NAME: credit_scoring_ci
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/MLProject/mlruns
          DO_TUNING: "1"
          TARGET_COL: "Y"
        run: |
          cd MLProject
          mlflow run . --env-manager=local
          echo "=== last_run_id.txt ==="
          cat last_run_id.txt

      - name: Build Docker Image with MLflow (from last_run_id.txt)
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/MLProject/mlruns
        run: |
          cd MLProject
          RUN_ID=$(cat last_run_id.txt)
          echo "Using RUN_ID: $RUN_ID"
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n credit-scoring-mlflow

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag & Push Docker Image
        run: |
          docker tag credit-scoring-mlflow "${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-mlflow:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-mlflow:latest"